src/carts/urls.py
from django.conf.urls import url

from .views import (
		cart_home, 
		cart_update, 
		checkout_home, 
		checkout_done_view
	)

urlpatterns = [
	url(r'^$', cart_home, name='home'),
	url(r'^checkout/$', checkout_home, name='checkout'),
	url(r'^checkout/success$', checkout_done_view, name='success'),
	url(r'^update/$', cart_update, name='update'),
]

src/explorify/urls.py
from django.conf import settings
from django.conf.urls.static import static


from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LogoutView

from addresses.views import checkout_address_create_view, checkout_address_reuse_view
from accounts.views import LoginView, RegisterView, guest_register_view
from carts.views import cart_detail_api_view

from .views import home_page, about_page, contact_page

urlpatterns = [
	url(r'^$', home_page, name='home'),
	url(r'^about/$', about_page, name='about'),
	url(r'^contact/$', contact_page, name='contact'),
	url(r'^login/$', LoginView.as_view(), name='login'),
	url(r'^logout/$', LogoutView.as_view(), name='logout'),
	url(r'^register/$', RegisterView.as_view(), name='register'),
	url(r'^register/guest/$', guest_register_view, name='guest_register'),
	url(r'^api/cart/$', cart_detail_api_view, name='api-cart'),
	url(r'^cart/', include("carts.urls", namespace='cart')),
	url(r'^checkout/address/create/', checkout_address_create_view, name='checkout_address_create'),
	url(r'^checkout/address/reuse/', checkout_address_reuse_view, name='checkout_address_reuse'),
	url(r'^deals/', include("products.urls", namespace='products')),
	url(r'^categories/', include("products.urls_categories")),
	url(r'^search/', include("search.urls", namespace='search')),
	# url(r'^featured/(?P<pk>\d+)/$', ProductFeaturedDetailView.as_view()),
	url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
	urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/search/urls.py
from django.conf.urls import url

from .views import (SearchProductView, 
					)

urlpatterns = [
	url(r'^$', SearchProductView.as_view(), name='query'),
]

src/search/models.py
from django.db import models

# Create your models here.

src/search/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from products.models import Product

class SearchProductView(ListView):
	template_name = "search/view.html"

	def get_context_data(self, *args, **kwargs):
		context = super().get_context_data(*args, **kwargs)
		context['query'] = self.request.GET.get('q')
		return context

	def get_queryset(self, *args, **kwargs):
		request = self.request
		print(request.GET)
		query = request.GET.get('q')
		if query is not None:
			return Product.objects.search(query)
		return Product.objects.featured()

src/search/templates/search/snippets/search-form.html
<form class="form my-2 my-lg-0 search-form search-form" method='GET' action='{% url "search:query" %}'>
    <div class="input-group">
        <input type="text" class="form-control input-lg search-input" placeholder="Search Updeal ..." name="q" required="required" value="{{ request.GET.q }}">
        <div class="input-group-btn">
            <div class="input-group">
                <select class="form-control input-lg search-select">
                    <option>Select Your City</option>
                    <option>Karachi</option>
                    <option>Islamabad</option>
                    <option>Lahore</option>
                </select>
                <div class="input-group-btn">
                    <button type="submit" class="btn btn-lg btn-search btn-block">
                        <i class="fa fa-search font-16"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>
</form>