src/carts/urls.py
from django.conf.urls import url

from .views import (
		cart_home, 
		cart_update, 
		checkout_home, 
		checkout_done_view
	)

urlpatterns = [
	url(r'^$', cart_home, name='home'),
	url(r'^checkout/$', checkout_home, name='checkout'),
	url(r'^checkout/success$', checkout_done_view, name='success'),
	url(r'^update/$', cart_update, name='update'),
]

src/explorify/urls.py
from django.conf import settings
from django.conf.urls.static import static


from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LogoutView

from addresses.views import checkout_address_create_view, checkout_address_reuse_view
from accounts.views import LoginView, RegisterView, guest_register_view
from carts.views import cart_detail_api_view

from .views import home_page, about_page, contact_page

urlpatterns = [
	url(r'^$', home_page, name='home'),
	url(r'^about/$', about_page, name='about'),
	url(r'^contact/$', contact_page, name='contact'),
	url(r'^login/$', LoginView.as_view(), name='login'),
	url(r'^logout/$', LogoutView.as_view(), name='logout'),
	url(r'^register/$', RegisterView.as_view(), name='register'),
	url(r'^register/guest/$', guest_register_view, name='guest_register'),
	url(r'^api/cart/$', cart_detail_api_view, name='api-cart'),
	url(r'^cart/', include("carts.urls", namespace='cart')),
	url(r'^checkout/address/create/', checkout_address_create_view, name='checkout_address_create'),
	url(r'^checkout/address/reuse/', checkout_address_reuse_view, name='checkout_address_reuse'),
	url(r'^deals/', include("products.urls", namespace='products')),
	url(r'^categories/', include("products.urls_categories")),
	url(r'^search/', include("search.urls", namespace='search')),
	# url(r'^featured/(?P<pk>\d+)/$', ProductFeaturedDetailView.as_view()),
	url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
	urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/products/urls.py
from django.conf.urls import url

from .views import (ProductListView, 
					ProductDetailView,
					product_create_view,
					)

urlpatterns = [
	url(r'^$', ProductListView.as_view(), name='list'),
	url(r'^create/$', product_create_view),
	url(r'^(?P<slug>[\w-]+)/$', ProductDetailView.as_view(), name='detail'),
]

src/templates/base/css.html
{% load static %}
<!-- Fontawesome CSS -->
<link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static 'css/vendors/font-awesome/css/font-awesome.min.css' %}">

<!-- Bootstrap CSS -->
<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous"> -->
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">

<link href="{% static 'css/custom.css' %}" rel="stylesheet">

<!-- jquery confirm CSS -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.css">

<!-- Linearicons -->
<link href="{% static 'css/vendors/linearicons/css/linearicons.css' %}" rel="stylesheet">

<!-- Owl Carousel -->
<link href="{% static 'css/vendors/owl-carousel/owl.carousel.min.css' %}" rel="stylesheet">
<link href="{% static 'css/vendors/owl-carousel/owl.theme.min.css' %}" rel="stylesheet">

<!-- Flex Slider -->
<link href="{% static 'css/vendors/flexslider/flexslider.css' %}" rel="stylesheet">

<!-- Template Stylesheet -->
<link href="{% static 'css/base.css' %}" rel="stylesheet">
<link href="{% static 'css/style.css' %}" rel="stylesheet">

src/templates/base/footer.html
{% load static %}

<section class="footer-top-area pt-70 pb-30 pos-r bg-blue">
    <div class="container">
        <div class="row row-tb-20">
            <div class="col-sm-12 col-md-7">
                <div class="row row-tb-20">
                    <div class="footer-col col-sm-6">
                        <div class="footer-about">
                            <img class="mb-40" src="{% static 'img/updeal-logo.png' %}" width="150" alt="">
                            <p class="color-light">Discover and save on 1000s of great deals at nearby restaurants, spas, things to do, shopping, travel and more in Pakistan. Updeal: Own the Experience.</p>
                        </div>
                    </div>
                    <div class="footer-col col-sm-6">
                        <div class="footer-top-twitter">
                            <h2 class="color-lighter">Twitter Feed</h2>
                            <ul class="twitter-list">
                                <li class="single-twitter">
                                    <p class="color-light"><i class="ico fa fa-twitter"></i><a href="index.html#">@masum_rana :</a> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore in reprehenderit.</p>
                                </li>
                                <li class="single-twitter">
                                    <p class="color-light"><i class="ico fa fa-twitter"></i><a href="index.html#">@masum_rana :</a> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ratione id corrupti iusto cupiditate omnis.</p>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-12 col-md-5">
                <div class="row row-tb-20">
                    <div class="footer-col col-sm-6">
                        <div class="footer-links">
                            <h2 class="color-lighter">Quick Links</h2>
                            <ul>
                                <li><a href="deals_grid.html">Latest Deals</a>
                                </li>
                                <li><a href="coupons_grid.html">Newest Coupons</a>
                                </li>
                                <li><a href="contact_us_02.html">Contact Us</a>
                                </li>
                                <li><a href="404.html">Error 404</a>
                                </li>
                                <li><a href="terms_conditions.html">Terms of Use</a>
                                </li>
                                <li><a href="faq.html">FAQs</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="footer-col col-sm-6">
                        <div class="footer-top-instagram instagram-widget">
                            <h2>Instagram Widget</h2>
                            <div class="row row-tb-5 row-rl-5">


                                <div class="instagram-widget__item col-xs-4">
                                    <img src="{% static 'img/instagram/instagram_01.jpg' %}" alt="">
                                </div>


                                <div class="instagram-widget__item col-xs-4">
                                    <img src="{% static 'img/instagram/instagram_02.jpg' %}" alt="">
                                </div>


                                <div class="instagram-widget__item col-xs-4">
                                    <img src="{% static 'img/instagram/instagram_03.jpg' %}" alt="">
                                </div>


                                <div class="instagram-widget__item col-xs-4">
                                    <img src="{% static 'img/instagram/instagram_04.jpg' %}" alt="">
                                </div>


                                <div class="instagram-widget__item col-xs-4">
                                    <img src="{% static 'img/instagram/instagram_05.jpg' %}" alt="">
                                </div>


                                <div class="instagram-widget__item col-xs-4">
                                    <img src="{% static 'img/instagram/instagram_06.jpg' %}" alt="">
                                </div>


                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xs-12">
                <div class="payment-methods t-center">
                    <span><img src="{% static 'img/icons/payment/paypal.jpg' %}" alt=""></span>
                    <span><img src="{% static 'img/icons/payment/visa.jpg' %}" alt=""></span>
                    <span><img src="{% static 'img/icons/payment/mastercard.jpg' %}" alt=""></span>
                    <span><img src="{% static 'img/icons/payment/discover.jpg' %}" alt=""></span>
                    <span><img src="{% static 'img/icons/payment/american.jpg' %}" alt=""></span>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- –––––––––––––––[ FOOTER ]––––––––––––––– -->
<footer id="mainFooter" class="main-footer">
    <div class="container">
        <div class="row">
            <p>Copyright &copy; 2018 updeal.pk | All rights reserved.</p>
        </div>
    </div>
</footer>
<!-- –––––––––––––––[ END FOOTER ]––––––––––––––– -->

src/templates/base/js.html
{% load static %}
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script> <!-- slim ver and integrity attr removed for ajax -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>
<!-- <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script> -->

<!-- jquery confirm -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.js"></script>

<!-- Django Secure AJAX JS -->
<script src="{% static 'js/csrf.ajax.js' %}"></script>

<!-- explorify Custom JS -->
<script src="{% static 'js/explorify.js' %}"></script>


<!-- ––––––––––––––––––––––––––––––––––––––––– -->
<!-- JavaScript Plugins                        -->
<!-- ––––––––––––––––––––––––––––––––––––––––– -->
<!-- (!) Include all compiled plugins (below), or include individual files as needed -->

<!-- Modernizer JS -->
<script src="{% static 'js/vendors/modernizr/modernizr-2.6.2.min.js' %}"></script>

<!-- Owl Carousel -->
<script type="text/javascript" src="{% static 'js/vendors/owl-carousel/owl.carousel.min.js' %}"></script>

<!-- FlexSlider -->
<script type="text/javascript" src="{% static 'js/vendors/flexslider/jquery.flexslider-min.js' %}"></script>

<!-- Coutdown -->
<script type="text/javascript" src="{% static 'js/vendors/countdown/jquery.countdown.js' %}"></script>

<!-- ––––––––––––––––––––––––––––––––––––––––– -->
<!-- Custom Template JavaScript                   -->
<!-- ––––––––––––––––––––––––––––––––––––––––– -->
<script type="text/javascript" src="{% static 'js/main.js' %}"></script>

src/templates/base/navbar.html
{% url 'home' as home_url %}
{% url 'products:list' as product_list_url %}
{% url 'contact' as contact_url %}
{% url 'about' as about_url %}
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
{% url 'register' as register_url %}

{% url 'cart:home' as cart_url %}

<!-- Navbar Start -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
  <div class="container">
  <a class="navbar-brand" href="{% url 'home' %}">explorify</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {% if request.path == home_url %}active{% endif %}">
        <a class="nav-link" href="{{ home_url }}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item {% if request.path == product_list_url %}active{% endif %}">
        <a class="nav-link" href="{{ product_list_url }}">Products</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Categories
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="/categories/electronics/">Electronics</a>
          <a class="dropdown-item" href="/categories/computing/">Computing</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="/categories/mens-clothing/">Mens Fashion</a>
          <a class="dropdown-item" href="/categories/womens-clothing/">Womens Fashion</a>
        </div>
      </li>
      <li class="nav-item {% if request.path == contact_url %}active{% endif %}">
        <a class="nav-link" href="{{ contact_url }}">Contact</a>
      </li>
      <li class="nav-item {% if request.path == about_url %}active{% endif %}">
        <a class="nav-link" href="{{ about_url }}">About</a>
      </li>
      {% if request.user.is_authenticated %}
      <li class="nav-item {% if request.path == logout_url %}active{% endif %}">
        <a class="nav-link" href="{{ logout_url }}">Logout</a>
      </li>
      {% else %}
      <li class="nav-item {% if request.path == login_url %}active{% endif %}">
        <a class="nav-link" href="{{ login_url }}">Login</a>
      </li>
      <li class="nav-item {% if request.path == register_url %}active{% endif %}">
        <a class="nav-link" href="{{ register_url }}">Register</a>
      </li>
      </li>
      {% endif %}
      <li class="nav-item {% if request.path == cart_url %}active{% endif %}">
        <a class="nav-link" href="{{ cart_url }}"><span class="navbar-cart-count">{{ request.session.cart_items_count }}</span> <i class="fas fa-shopping-cart"></i></a>
      </li>
    </ul>
    {% include 'search/snippets/search-form.html' %}
  </div>
</div>
</nav>
<!--Navbar End -->