src/carts/urls.py
from django.conf.urls import url

from .views import (
		cart_home, 
		cart_update, 
		checkout_home, 
		checkout_done_view
	)

urlpatterns = [
	url(r'^$', cart_home, name='home'),
	url(r'^checkout/$', checkout_home, name='checkout'),
	url(r'^checkout/success$', checkout_done_view, name='success'),
	url(r'^update/$', cart_update, name='update'),
]

src/explorify/urls.py
from django.conf import settings
from django.conf.urls.static import static


from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LogoutView

from addresses.views import checkout_address_create_view, checkout_address_reuse_view
from accounts.views import LoginView, RegisterView, guest_register_view
from carts.views import cart_detail_api_view

from .views import home_page, about_page, contact_page

urlpatterns = [
	url(r'^$', home_page, name='home'),
	url(r'^about/$', about_page, name='about'),
	url(r'^contact/$', contact_page, name='contact'),
	url(r'^login/$', LoginView.as_view(), name='login'),
	url(r'^logout/$', LogoutView.as_view(), name='logout'),
	url(r'^register/$', RegisterView.as_view(), name='register'),
	url(r'^register/guest/$', guest_register_view, name='guest_register'),
	url(r'^api/cart/$', cart_detail_api_view, name='api-cart'),
	url(r'^cart/', include("carts.urls", namespace='cart')),
	url(r'^checkout/address/create/', checkout_address_create_view, name='checkout_address_create'),
	url(r'^checkout/address/reuse/', checkout_address_reuse_view, name='checkout_address_reuse'),
	url(r'^deals/', include("products.urls", namespace='products')),
	url(r'^categories/', include("products.urls_categories")),
	url(r'^search/', include("search.urls", namespace='search')),
	# url(r'^featured/(?P<pk>\d+)/$', ProductFeaturedDetailView.as_view()),
	url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
	urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/carts/models.py
from decimal import Decimal
from django.conf import settings
from django.db import models
from django.db.models.signals import pre_save, post_save, m2m_changed

from products.models import Product
User = settings.AUTH_USER_MODEL

class CartManager(models.Manager):
	def new_or_get(self, request):
		cart_id = request.session.get("cart_id", None)
		qs = self.get_queryset().filter(id=cart_id)
		if qs.count() == 1:
			new_obj = False
			print("Cart ID Exists", cart_id)
			cart_obj = qs.first()
			if request.user.is_authenticated() and cart_obj.user is None:
				cart_obj.user = request.user
				cart_obj.save()
		else:
			cart_obj = self.new(user=request.user)
			new_obj = True
			request.session["cart_id"] = cart_obj.id
		return cart_obj, new_obj

	def new(self, user=None):
		user_obj = None
		print("===========", user)
		if user is not None and user.is_authenticated():
			print(user)
			user_obj = user
		return self.model.objects.create(user=user_obj)

# class CartItem(models.Model):
# 	item = models.ForeignKey(Variation)
# 	quantity = models.PositiveIntegerField(default=1)

# 	def __str__(self):
# 		return str(self.item.title)

class Cart(models.Model):
	user 		= models.ForeignKey(User, null=True, blank=True)
	# items 		= models.ManyToManyField(Variation, through=CartItem)
	products 	= models.ManyToManyField(Product, blank=True)
	subtotal 	= models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
	total 		= models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
	updated 	= models.DateTimeField(auto_now=True)
	timestamp 	= models.DateTimeField(auto_now_add=True)

	objects = CartManager()

	def __str__(self):
		return str(self.id)

def m2m_changed_cart_receiver(sender, instance, action, *args, **kwargs):
	if action == "post_add" or action == "post_remove" or action == "post_clear":
		products = instance.products.all()
		total = 0
		for x in products:
			total += x.price
		if instance.subtotal != total:
			instance.subtotal = total
			instance.save()

m2m_changed.connect(m2m_changed_cart_receiver, sender=Cart.products.through)

def pre_save_cart_receiver(sender, instance, *args, **kwargs):
	if instance.subtotal > 0:
		updeal_profit = Decimal(.20) # 20%
		increased_amount = Decimal(instance.subtotal) * updeal_profit
		instance.total = Decimal(instance.subtotal) + increased_amount
	else:
		instance.total = 0.00

pre_save.connect(pre_save_cart_receiver, sender=Cart)

src/carts/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse

from accounts.forms import LoginForm, GuestForm
from accounts.models import GuestEmail
from addresses.models import Address
from addresses.forms import AddressForm
from billing.models import BillingProfile
from orders.models import Order
from products.models import Product
from .models import Cart

def cart_detail_api_view(request):
	cart_obj, new_obj = Cart.objects.new_or_get(request)
	products = [{
			"id": x.id,
			"url": x.get_absolute_url(),
			"name": x.title, 
			"price": x.price
			}
			for x in cart_obj.products.all()]
	cart_data = {"products": products, "subtotal": cart_obj.subtotal, "total": cart_obj.total}
	return JsonResponse(cart_data)


def cart_home(request):
	cart_obj, new_obj = Cart.objects.new_or_get(request)

	return render(request, "carts/cart.html", {"cart": cart_obj})


# for updating cart, if changed
def cart_update(request):
	product_id = request.POST.get('product_id')
	if product_id is not None:
		try:
			product_obj = Product.objects.get(id=product_id)
		except Product.DoesNotExist:
			print("Show message to user, product is gone?")
			redirect("cart:home")
		cart_obj, new_obj = Cart.objects.new_or_get(request)
		if product_obj in cart_obj.products.all():
			cart_obj.products.remove(product_obj)
			added = False
		else:
			cart_obj.products.add(product_obj)
			added = True
		request.session['cart_items_count'] = cart_obj.products.count()
		if request.is_ajax():
			print("Ajax request")
			json_data = {
				"added": added,
				"removed": not added,
				"cartItemCount": cart_obj.products.count(),
			}
			return JsonResponse(json_data, status=200) # HttpResponse
			# return JsonResponse({"message": "Error 400"}, status=400) # Django Rest Framework
	return redirect("cart:home")


def checkout_home(request):
	cart_obj, cart_created = Cart.objects.new_or_get(request)
	order_obj = None
	if cart_created or cart_obj.products.count() == 0:
		return redirect("cart:home")

	login_form = LoginForm()
	guest_form = GuestForm()
	address_form = AddressForm()
	shipping_address_id = request.session.get("shipping_address_id", None)

	billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(request)
	address_qs = None
	if billing_profile is not None:
		if request.user.is_authenticated():
			address_qs = Address.objects.filter(billing_profile=billing_profile)
		print(address_qs)
		order_obj, order_obj_created = Order.objects.new_or_get(billing_profile, cart_obj)
		if shipping_address_id:
			order_obj.shipping_address = Address.objects.get(id=shipping_address_id)
			order_obj.save()
			del request.session["shipping_address_id"]

	if request.method == "POST":
		"some check that order is done"
		is_done = order_obj.check_done()
		if is_done:
			order_obj.mark_paid()
			request.session["cart_items_count"] = 0
			del request.session["cart_id"]
			return redirect("cart:success")


	context = {
		"object": order_obj,
		"billing_profile": billing_profile,
		"login_form": login_form,
		"guest_form": guest_form,
		"address_form": address_form,
		"address_qs": address_qs,
	}
	return render(request, "carts/checkout.html", context)


def checkout_done_view(request):
	return render(request, "carts/checkout-done.html", {})

src/carts/templates/carts/cart.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="page-container">
    <div class="container">
        <div class="cart-area ptb-60">
            <div class="container">
                <div class="cart-wrapper">
                    <h3 class="h-title mb-30 t-uppercase">My Cart</h3>
                    {% if cart.products.exists %}
                    <table id="cart_list" class="cart-list mb-30">
                        <thead class="panel t-uppercase">
                            <tr>
                                <th>Product name</th>
                                <th>Unit price</th>
                                <th>Quantity</th>
                                <th>Sub total</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                        	{% for product in cart.products.all %}
                            <tr class="panel alert product-row">
                                <td>
                                    <div class="media-left is-hidden-sm-down">
                                        <figure class="product-thumb">
                                            <img src="{% static 'img/product_01.jpg' %}" alt="product">
                                        </figure>
                                    </div>
                                    <div class="media-body valign-middle">
                                        <h6 class="title mb-15 t-uppercase"><a href="{{ product.get_absolute_url }}">{{ product.title }}</a></h6>
                                        <div class="type font-12"><span class="t-uppercase">Desc : </span>{{ product.description|truncatewords:"20" }}</div>
                                    </div>
                                </td>
                                <td>{{ product.price }}</td>
                                <td>
                                    <input class="quantity-label" type="number" value="02">
                                </td>
                                <td>
                                    <div class="sub-total">{{ product.price }}</div>
                                </td>
                                <td>
                                	{% include 'carts/snippets/remove-product.html' with product_id=product.id %}
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    <div class="cart-item-remove-form" style="display: none;">
						{% include 'carts/snippets/remove-product.html' %}
					</div> 
                    <div class="cart-price">
                        <h5 class="t-uppercase mb-20">Cart total</h5>
                        <ul class="panel mb-20">
                            <li>
                                <div class="item-name">
                                    Subtotal
                                </div>
                                <div class="cart-subtotal price">
                                    Rs.{{ cart.subtotal }}
                                </div>
                            </li>
                            <li>
                                <div class="item-name">
                                    Shipping
                                </div>
                                <div class="price">
                                    20%
                                </div>
                            </li>
                            <li>
                                <div class="item-name">
                                    <strong class="t-uppercase">Order total</strong>
                                </div>
                                <div class="cart-total price">
                                    <span>Rs.{{ cart.total }}</span>
                                </div>
                            </li>
                        </ul>
                        <div class="t-right">
                            <a href="{% url 'cart:checkout' %}" class="btn btn-rounded btn-lg">CHECKOUT</a>
                        </div>
                    </div>
                    {% else %}
						<p class="lead">Cart is empty, Go shop some!</p>
					{% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

src/carts/templates/carts/checkout-done.html
{% extends "base.html" %}

{% block content %}
<div class="col-6 mx-auto py-5 text-center">
	<h1 class="display-1">Thank you for your order</h1>
</div>
{% endblock %}

src/carts/templates/carts/checkout.html
{% extends "base.html" %}

{% block content %}

{% url 'register' as register_url %}

<div class="page-container ptb-60">
    <div class="container">
    	{% if not billing_profile %}
        <section class="sign-area panel p-40">
        	<h3 class="h3 mb-20 h-title">Checkout</h3>
            <h3 class="sign-title">Sign In <small>Or <a href="{{ register_url }}" class="color-green">Sign Up</a></small></h3>
            <div class="row row-rl-0">
                <div class="col-sm-6 col-md-7 col-left">
                    <div class="p-40">
                    	{% include 'accounts/snippets/form.html' with form=login_form next_url=request.build_absolute_uri %}
                        <div class="form-group">
                            <a href="#" class="forgot-pass-link color-green">Forget Your Password?</a>
                        </div>
                        <div class="custom-checkbox mb-20">
                            <input type="checkbox" id="remember_account" checked>
                            <label class="color-mid" for="remember_account">Keep me signed in on this computer.</label>
                        </div>
                        <h3 class="sign-title">Continue as Guest</h3>
	            		{% url "guest_register" as guest_register_url %}
	            		{% include 'accounts/snippets/form.html' with form=guest_form next_url=request.build_absolute_uri action_url=guest_register_url %}
                    </div>
                    <span class="or">Or</span>
                </div>
                <div class="col-sm-6 col-md-5 col-right">
                    <div class="social-login p-40">
                        <div class="mb-20">
                            <button class="btn btn-lg btn-block btn-social btn-facebook"><i class="fa fa-facebook-square"></i>Sign In with Facebook</button>
                        </div>
                        <div class="mb-20">
                            <button class="btn btn-lg btn-block btn-social btn-twitter"><i class="fa fa-twitter"></i>Sign In with Twitter</button>
                        </div>
                        <div class="mb-20">
                            <button class="btn btn-lg btn-block btn-social btn-google-plus"><i class="fa fa-google-plus"></i>Sign In with Google</button>
                        </div>
                        <div class="custom-checkbox mb-20">
                            <input type="checkbox" id="remember_social" checked>
                            <label class="color-mid" for="remember_social">Keep me signed in on this computer.</label>
                        </div>
                        <div class="text-center color-mid">
                            Need an Account ? <a href="{{ register_url }}" class="color-green">Create Account</a>
                        </div>
                    </div>
                </div>
            </div>
        </section>
		{% else %}
			{% if not object.shipping_address %}
				<div class="row row-rl-10 row-tb-20">
                    <div class="page-content col-xs-12 col-sm-8 col-md-9">

                        <!-- Checkout Area -->
                        <section class="section checkout-area panel prl-30 pt-20 pb-40">
                            <h2 class="h2 mb-20 h-title">Shipping Information</h2>
                            <div class="mb-30">
	                            {% url "checkout_address_create" as checkout_address_create %}
								{% include 'addresses/form.html' with form=address_form next_url=request.build_absolute_uri action_url=checkout_address_create %}
							</div>
                        </section>
                        <!-- End Checkout Area -->

                    </div>


                    <div class="page-sidebar col-xs-12 col-sm-4 col-md-3">

                        <!-- Cart Sidebar -->
                        <aside class="sidebar blog-sidebar">
                        	<div class="row row-tb-10">
                                <div class="col-xs-12">
                                    <!-- Recent Posts -->
                                    <div class="widget checkout-widget panel p-20">
                                        <div class="widget-body">
					                    	{% url "checkout_address_reuse" as checkout_address_reuse %}
											{% include 'addresses/prev_addresses.html' with address_qs=address_qs next_url=request.build_absolute_uri action_url=checkout_address_reuse %}
										</div>
									</div>
								</div>
							</div>
                        	
                            <div class="row row-tb-10">
                                <div class="col-xs-12">
                                    <!-- Recent Posts -->
                                    <div class="widget checkout-widget panel p-20">
                                        <div class="widget-body">
                                            <table class="table mb-15">
                                                <tbody>
                                                    <tr>
                                                        <td class="color-mid">Total products</td>
                                                        <td>Rs.{{ object.cart.total }}</td>
                                                    </tr>
                                                    <tr>
                                                        <td class="color-mid">Shipping</td>
                                                        <td>20%</td>
                                                    </tr>
                                                    <tr>
                                                        <td class="color-mid">Total tax</td>
                                                        <td>Rs.0.00</td>
                                                    </tr>
                                                    <tr class="font-15">
                                                        <td class="color-mid">Total</td>
                                                        <td class="color-green">Rs.{{ object.total }}</td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                            <a href="{% url 'cart:home' %}" class="btn btn-info btn-block btn-sm">Edit Cart</a>
                                        </div>
                                    </div>
                                    <!-- End Recent Posts -->
                                </div>
                            </div>
                        </aside>
                        <!-- End Cart Sidebar -->
                    </div>
                </div>
			{% else %}
				<div class="row row-rl-10 row-tb-20">
                    <div class="page-content col-xs-12 col-sm-8 col-md-9">

                        <!-- Checkout Area -->
                        <section class="section checkout-area panel prl-30 pt-20 pb-40">
                            <h2 class="h3 mb-20 h-title">Finalize Checkout</h2>
                            <div class="mb-20">
	                            <p>Cart Items: {% for product in object.cart.products.all %}{{ product }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>
								<p>Shipping Address: {{ object.shipping_address.get_address }}</p>
								<p>Cart Total: {{ object.cart.total }}</p>
								<p>Shipping Total: {{ object.shipping_total }}</p>
								<p>Order Total: {{ object.total }}</p>
								<form class="form" method="POST" action="">{% csrf_token %}
									<button class="btn btn-lg btn-rounded mr-10" type="Submit">Checkout</button>
								</form>
							</div>
                        </section>
                        <!-- End Checkout Area -->

                    </div>
                    <div class="page-sidebar col-xs-12 col-sm-4 col-md-3">

                        <!-- Cart Sidebar -->
                        <aside class="sidebar blog-sidebar">
                            <div class="row row-tb-10">
                                <div class="col-xs-12">
                                    <!-- Recent Posts -->
                                    <div class="widget checkout-widget panel p-20">
                                        <div class="widget-body">
                                            <table class="table mb-15">
                                                <tbody>
                                                    <tr>
                                                        <td class="color-mid">Total products</td>
                                                        <td>Rs.{{ object.cart.total }}</td>
                                                    </tr>
                                                    <tr>
                                                        <td class="color-mid">Shipping</td>
                                                        <td>20%</td>
                                                    </tr>
                                                    <tr>
                                                        <td class="color-mid">Total tax</td>
                                                        <td>Rs.0.00</td>
                                                    </tr>
                                                    <tr class="font-15">
                                                        <td class="color-mid">Total</td>
                                                        <td class="color-green">Rs.{{ object.total }}</td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                            <a href="{% url 'cart:home' %}" class="btn btn-info btn-block btn-sm">Edit Cart</a>
                                        </div>
                                    </div>
                                    <!-- End Recent Posts -->
                                </div>
                            </div>
                        </aside>
                        <!-- End Cart Sidebar -->
                    </div>
                </div>
			{% endif %}
    	{% endif %}
    </div>
</div>



{% endblock %}