src/carts/urls.py
from django.conf.urls import url

from .views import (
		cart_home, 
		cart_update, 
		checkout_home, 
		checkout_done_view
	)

urlpatterns = [
	url(r'^$', cart_home, name='home'),
	url(r'^checkout/$', checkout_home, name='checkout'),
	url(r'^checkout/success$', checkout_done_view, name='success'),
	url(r'^update/$', cart_update, name='update'),
]

src/explorify/urls.py
from django.conf import settings
from django.conf.urls.static import static


from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LogoutView

from addresses.views import checkout_address_create_view, checkout_address_reuse_view
from accounts.views import LoginView, RegisterView, guest_register_view
from carts.views import cart_detail_api_view

from .views import home_page, about_page, contact_page

urlpatterns = [
	url(r'^$', home_page, name='home'),
	url(r'^about/$', about_page, name='about'),
	url(r'^contact/$', contact_page, name='contact'),
	url(r'^login/$', LoginView.as_view(), name='login'),
	url(r'^logout/$', LogoutView.as_view(), name='logout'),
	url(r'^register/$', RegisterView.as_view(), name='register'),
	url(r'^register/guest/$', guest_register_view, name='guest_register'),
	url(r'^api/cart/$', cart_detail_api_view, name='api-cart'),
	url(r'^cart/', include("carts.urls", namespace='cart')),
	url(r'^checkout/address/create/', checkout_address_create_view, name='checkout_address_create'),
	url(r'^checkout/address/reuse/', checkout_address_reuse_view, name='checkout_address_reuse'),
	url(r'^deals/', include("products.urls", namespace='products')),
	url(r'^categories/', include("products.urls_categories")),
	url(r'^search/', include("search.urls", namespace='search')),
	# url(r'^featured/(?P<pk>\d+)/$', ProductFeaturedDetailView.as_view()),
	url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
	urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/products/urls.py
from django.conf.urls import url

from .views import (ProductListView, 
					ProductDetailView,
					product_create_view,
					)

urlpatterns = [
	url(r'^$', ProductListView.as_view(), name='list'),
	url(r'^create/$', product_create_view),
	url(r'^(?P<slug>[\w-]+)/$', ProductDetailView.as_view(), name='detail'),
]

src/products/models.py
import os

from django.db import models
from django.db.models import Q
from django.db.models.signals import pre_save, post_save
from django.urls import reverse
from django.utils.text import slugify

from explorify.utils import unique_slug_generator


class ProductQuerySet(models.query.QuerySet):
	def active(self):
		return self.filter(active=True)

	def featured(self):
		return self.filter(featured=True, active=True)

	def search(self, query):
		lookups = (Q(title__icontains=query) | 
					Q(description__icontains=query) | 
					Q(price__icontains=query)|
					Q(tag__title__icontains=query)) # related tags
		return self.filter(lookups).distinct()


class ProductManager(models.Manager):
	def get_queryset(self):
		return ProductQuerySet(self.model, using=self._db)

	def all(self):
		return self.get_queryset().active()

	def featured(self): #Product.objects.featured()
		return self.get_queryset().featured()

	def get_related(self, instance):
		products_one = self.get_queryset().filter(categories__in=instance.categories.all())
		products_two = self.get_queryset().filter(default=instance.default)
		qs = (products_one | products_two).exclude(id=instance.id).distinct()
		return qs

	def get_by_id(self, id):
		qs = self.get_queryset().filter(id=id) #Product.objects == self.get_queryset()
		if qs.count() == 1:
			return qs.first()
		return None

	def search(self, query):
		return self.get_queryset().active().search(query)


class Product(models.Model):
	title = models.CharField(max_length=150)
	slug = models.SlugField(blank=True, unique=True)
	description = models.TextField()
	# summary = models.TextField()
	price = models.DecimalField(decimal_places=2, max_digits=20)
	active = models.BooleanField(default=True)
	featured = models.BooleanField(default=False)
	timestamp = models.DateTimeField(auto_now_add=True)
	categories = models.ManyToManyField('Category', blank=True)
	default = models.ForeignKey('Category', related_name='default_category', null=True, blank=True)

	objects = ProductManager()

	def get_absolute_url(self):
		# return "{slug}/".format(slug=self.slug)
		return reverse("products:detail", kwargs={"slug": self.slug})

	def get_image_url(self):
		img = self.productimage_set.first()
		if img:
			return img.image.url
		else: img #None

	def __str__(self):
		return self.title


def product_pre_save_receiver(sender, instance, *args, **kwargs):
	if not instance.slug:
		instance.slug = unique_slug_generator(instance)

pre_save.connect(product_pre_save_receiver, sender=Product)


class Variation(models.Model):
	product = models.ForeignKey(Product)
	title = models.CharField(max_length=120)
	price = models.DecimalField(decimal_places=2, max_digits=20)
	sell_price = models.DecimalField(decimal_places=2, max_digits=20, null=True, blank=True)
	active = models.BooleanField(default=True)
	inventory = models.IntegerField(null=True, blank=True) # refers none == unlimited amount


	def __str__(self):
		return self.title

	def get_price(self):
		if self.sell_price is not None:
			return self.sell_price

		else:
			return self.price

	def get_absolute_url(self):
		return self.product.get_absolute_url()

# whenever the PRODUCT model data is posted for save, it'll callback to this receiver
def product_post_saved_receiver(sender, instance, created, *args, **kwargs): # receiver function
	product = instance
	variations = product.variation_set.all()
	# variations = Variation.objects.filter(product=product) # same as above
	if variations.count() == 0:
		new_var = Variation()
		new_var.product = product
		new_var.title = "Default"
		new_var.price = product.price
		new_var.save()
	# print(sender)
	# print(instance)
	# print(created)

post_save.connect(product_post_saved_receiver, sender=Product) # connecting receiver to signal


def get_filename_ext(filepath):
	base_name = os.path.basename(filepath)
	name, ext = os.path.splitext(base_name)
	return name, ext

# ISSUE TO RESOLVE: image isn't deleting when object get destroyed
def image_upload_to(instance, filename):
	title = instance.product.title
	slug = slugify(title)
	name, ext = get_filename_ext(filename)
	new_filename = "{}-{}{}".format(slug, instance.id, ext) # also add random numbers
	return "products/{}/{}".format(slug, new_filename)


class ProductImage(models.Model):
	product = models.ForeignKey(Product)
	image = models.ImageField(upload_to=image_upload_to)

	def __str__(self):
		return self.product.title


class Category(models.Model):
	title = models.CharField(max_length=120, unique=True)
	slug = models.SlugField(unique=True)
	description = models.TextField(null=True, blank=True)
	active = models.BooleanField(default=True)
	timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse("category_detail", kwargs={"slug": self.slug})

src/products/forms.py
from django import forms

from .models import Product, Variation


class ProductForm(forms.ModelForm):
	class Meta:
		model = Product
		fields = [
			"title",
			"description",
			"price",
			"categories",
			"default",
		]


src/products/views.py
import random

from django.views.generic import ListView, DetailView
from django.shortcuts import render, get_object_or_404

from analytics.mixins import ObjectViewedMixin
from .mixins import StaffRequiredMixin
from .models import Product, Category
from .forms import ProductForm
from carts.models import Cart


def product_create_view(request):
	form = ProductForm(request.POST or None)
	if form.is_valid():
		form.save()

	context = {
		'form': form
	}
	return render(request, "products/product_create.html", context)


# class ProductInventoryView(CreateView):
# 	form_class = ProductInventoryForm
# 	template_name = 'products/inventory.html'
# 	success_url = '/products/'


class ProductFeaturedDetailView(ObjectViewedMixin, DetailView):
	queryset = Product.objects.all().featured()
	template_name = "products/product_detail.html"

	# def get_queryset(self, *args, **kwargs):
	# 	request = self.request
	# 	return Product.objects.featured()

class ProductListView(ListView):
	queryset = Product.objects.all()

	def get_context_data(self, *args, **kwargs):
		context = super().get_context_data(*args, **kwargs)
		cart_obj, new_obj = Cart.objects.new_or_get(self.request)
		context['cart'] = cart_obj
		return context

	def get_queryset(self, *args, **kwargs): #also get_queryset could be used
		request = self.request
		return Product.objects.all()


class ProductDetailView(ObjectViewedMixin, DetailView):
	queryset = Product.objects.all()
	
	def get_context_data(self, *args, **kwargs):
		context = super().get_context_data(*args, **kwargs)
		instance = self.get_object()
		context["related"] = sorted(Product.objects.get_related(instance)[:6], key=lambda x: random.random())
		cart_obj, new_obj = Cart.objects.new_or_get(self.request)
		print("---------------")
		print(cart_obj, new_obj)
		context["cart"] = cart_obj
		return context

	def get_object(self, *args, **kwargs):
		instance = self.get_object()
		ObjectViewedMixin
		# object_viewed_signal.send(instance.__class__, instance=instance, request=request)


class CategoryListView(ListView):
	queryset = Category.objects.all()


class CategoryDetailView(ObjectViewedMixin, DetailView):
	queryset = Category.objects.all()

	def get_context_data(self, *args, **kwargs):
		context = super().get_context_data(*args, **kwargs)
		obj = self.get_object()
		product_set = obj.product_set.all()
		default_products = obj.default_category.all()
		products = (product_set | default_products).distinct()
		context["products"] = products
		return context

# class ProductDetailView(DetailView):
# 	# queryset = Product.objects.all()
# 	# template_name = "products/product_detail.html"

# 	def get_context_data(self, *args, **kwargs):
# 		context = super().get_context_data(*args, **kwargs)
# 		# print(context)
# 		return context

# 	def get_object(self, *args, **kwargs): #also get_queryset could be used
# 		request = self.request
# 		pk = self.kwargs.get("pk")
# 		instance = Product.objects.get_by_id(pk)
# 		if instance is None:
# 			raise Http404("Product doesn't exist")
# 		return instance

src/products/templates/products/snippets/card.html
{% load static %}

<div class="col-xs-12">
    <div class="coupon-single panel t-center t-sm-left">
		<div class="row row-sm-cell row-tb-0 row-rl-0">
		    <div class="col-sm-5">
		        <figure class="p-15">
		        	{% if instance.productimage_set.count > 0 %}
		        	<a href="{{ instance.get_absolute_url }}">
		        		<img class="store-logo" src="{{ instance.productimage_set.first.image.url }}" alt={{ instance.title }}>
		        	</a>
		        	{% else %}
		        	<a href="{{ instance.get_absolute_url }}">
		        		<img class="store-logo" src="{% static 'img/no-image.jpg' %}" alt={{ instance.title }}>
		        	</a>
		        	{% endif %}
		        </figure>
		    </div>
		    <!-- end col -->
		    <div class="col-sm-7">
		        <div class="panel-body">
		            <ul class="deal-meta list-inline mb-10">
		                <li class="color-muted"><i class="ico fa fa-map-marker mr-5"></i>Karachi</li>
		                <li class="color-muted"><i class="ico lnr lnr-users mr-5"></i>425 Bought</li>
		            </ul>
		            <h5 class="deal-title mb-10">
		             <a href="{{ instance.get_absolute_url }}">{{ instance.title }}</a>
		          </h5>
		            <p class="mb-15 color-muted font-12"><i class="lnr lnr-clock mr-10"></i>Expires in 1 day 30 hours</p>
		            <div style="text-align: right">
		            	{% include 'products/snippets/update-cart.html' with product=instance cart=cart %}
		            </div>
		            
		            <div class="deal-price pos-r mb-15">
                        <h3 class="price ptb-5 text-right">
                        	{% if instance.variation_set.first.sell_price %}
								<span class="price-sale">${{ instance.variation_set.first.price }}</span>${{ instance.variation_set.first.sell_price }}
							{% else %}
								{{ instance.variation_set.first.price }}
							{% endif %}
                        </h3>
                    </div>
		            <!-- <div class="showcode">
		                <button class="show-code btn btn-sm btn-block" data-toggle="modal" data-target="#coupon_2">Show Code</button>
		                <div class="coupon-hide">X455-17GT-OL58</div>
		            </div> -->
		        </div>
		    </div>
		    <!-- end col -->
		</div>
	</div>
</div>





<!-- <div class="card" style="width: 18rem;">
	{% if instance.productimage_set.count > 0 %}
		<a href="{{ instance.get_absolute_url }}">
			<img class="card-img-top" src="{{ instance.productimage_set.first.image.url }}" alt={{ instance.title }}>
		</a>
	{% endif %}
	<div class="card-body">
	<h5 class="card-title">{{ instance.title }}</h5>
	<p class="card-text">{{ instance.description|truncatewords:12 }}</p>
	<a href="{{ instance.get_absolute_url }}" class="btn btn-primary">View</a>
		{% include 'products/snippets/update-cart.html' with product=instance cart=cart %}
	
	</div>
</div> -->

src/products/templates/products/snippets/update-cart.html
<form class="form-product-ajax" method='POST' action='{% url "cart:update" %}' data-endpoint='{% url "cart:update" %}' class="form"> {% csrf_token %}
	<input type="hidden" name="product_id" value="{{ product.id }}" />
	<span class="submit-span">
	{% if product in cart.products.all %}
		In Cart <button class="btn btn-link">Remove?</button>
	{% else %}
		<button class="{% if loc == 'single' %}btn btn-block btn-lg{% else %}btn btn-success{% endif %}" style="height: 34px; padding: 5px 15px; font-size: 12px; line-height: 20px; border-radius: 3px;"><i class="fa fa-shopping-cart font-16 mr-10"></i> Add to Cart</button>
	{% endif %}
	</span>
</form>